---
title: Die Throw-Anweisung kann außerhalb einer Catch-Anweisung oder innerhalb einer Finally-Anweisung den Operanden nicht auslassen.
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 8f94577e1ace3daeab9025056aa1a313331a51e1
ms.sourcegitcommit: bef803e2025642df39f2f1e046767d89031e0304
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 02/15/2019
ms.locfileid: "56305037"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="605dc-102">Die Throw-Anweisung kann außerhalb einer Catch-Anweisung oder innerhalb einer Finally-Anweisung den Operanden nicht auslassen.</span><span class="sxs-lookup"><span data-stu-id="605dc-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>
<span data-ttu-id="605dc-103">`Throw` -Anweisungen außerhalb einer `Catch` -Anweisung müssen den Namen eines Ausnahmeobjekts angeben.</span><span class="sxs-lookup"><span data-stu-id="605dc-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="605dc-104">**Fehler-ID:** BC30666</span><span class="sxs-lookup"><span data-stu-id="605dc-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="605dc-105">So beheben Sie diesen Fehler</span><span class="sxs-lookup"><span data-stu-id="605dc-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="605dc-106">Geben Sie den Namen eines von `System.Exception`abgeleiteten Ausnahmeobjekts an.</span><span class="sxs-lookup"><span data-stu-id="605dc-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="605dc-107">Strukturieren Sie den Code neu, damit sich die `Throw` -Anweisung innerhalb eines `Catch` -Blocks befindet.</span><span class="sxs-lookup"><span data-stu-id="605dc-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="605dc-108">Siehe auch</span><span class="sxs-lookup"><span data-stu-id="605dc-108">See also</span></span>
- [<span data-ttu-id="605dc-109">Throw-Anweisung</span><span class="sxs-lookup"><span data-stu-id="605dc-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)
- [<span data-ttu-id="605dc-110">Try...Catch...Finally-Anweisung</span><span class="sxs-lookup"><span data-stu-id="605dc-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="605dc-111">Behandeln und Auslösen von Ausnahmen in .NET</span><span class="sxs-lookup"><span data-stu-id="605dc-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
